//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaticSoft.Web.HKSJ_USERS {
    
    
    /// <summary>
    /// Modify 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Modify {
        	protected global::System.Web.UI.WebControls.Label lblID;
		protected global::System.Web.UI.WebControls.TextBox txtUserName;
	protected global::System.Web.UI.WebControls.Label lblLoginName;
		protected global::System.Web.UI.WebControls.TextBox txtPassWord;
		protected global::System.Web.UI.WebControls.TextBox txtPlane;
		protected global::System.Web.UI.WebControls.TextBox txtphone;
		protected global::System.Web.UI.WebControls.TextBox txtMail;
		protected global::System.Web.UI.WebControls.TextBox txtcardNo;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
