//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaticSoft.Web.HKSJ_USERS {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblID;
	protected global::System.Web.UI.WebControls.Label lblUserName;
	protected global::System.Web.UI.WebControls.Label lblLoginName;
	protected global::System.Web.UI.WebControls.Label lblPassWord;
	protected global::System.Web.UI.WebControls.Label lblPlane;
	protected global::System.Web.UI.WebControls.Label lblphone;
	protected global::System.Web.UI.WebControls.Label lblMail;
	protected global::System.Web.UI.WebControls.Label lblcardNo;


       
    }
}
