//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaticSoft.Web.HKSJ_Clients {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblid;
	protected global::System.Web.UI.WebControls.Label lbltitle;
	protected global::System.Web.UI.WebControls.Label lblsoftName;
	protected global::System.Web.UI.WebControls.Label lblcontent;
	protected global::System.Web.UI.WebControls.Label lblliaisonPhone;
	protected global::System.Web.UI.WebControls.Label lblliaisonPeple;
	protected global::System.Web.UI.WebControls.Label lbldate;
	protected global::System.Web.UI.WebControls.Label lblpeple;


       
    }
}
