//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_ModelFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }


        //处理foreign key限制
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //http://www.cnblogs.com/oppoic/p/ef_one-to-one_one-to-many_many-to-many_cascadedelete.html
            
        }

        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<R_Department_User> R_Department_User { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Class> Class { get; set; }
    }
}
