//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaticSoft.Web.HKSJ_Relationship {
    
    
    /// <summary>
    /// Add 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Add 
    {
        
		protected global::System.Web.UI.WebControls.TextBox txtAddress;
		protected global::System.Web.UI.WebControls.TextBox txtZip;
		protected global::System.Web.UI.WebControls.TextBox txtplane;
		protected global::System.Web.UI.WebControls.TextBox txtFax;
		protected global::System.Web.UI.WebControls.TextBox txtQQ_MSN;
		protected global::System.Web.UI.WebControls.TextBox txtDate;
		protected global::System.Web.UI.WebControls.TextBox txtpeople;
	protected global::System.Web.UI.WebControls.Button btnSave;
	protected global::System.Web.UI.WebControls.Button btnCancel;


        
    }
}
